# Configuración de Nginx para Laravel

server {
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/public;

    # Logs
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Client body size (para uploads)
    client_max_body_size 20M;

    # Configuración para Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesar archivos PHP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Cacheo de archivos estáticos
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Denegar acceso a archivos ocultos
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
